# Generated by Django 3.2.3 on 2021-05-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='datetime',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='datetime',
            new_name='created_time',
        ),
    ]
