# Generated by Django 3.2.3 on 2021-05-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subjects',
            field=models.ForeignKey(default='Default', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizapp.subject'),
            preserve_default=False,
        ),
    ]
