# Generated by Django 3.2.3 on 2021-05-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_quiz_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='subjects',
            new_name='subject',
        ),
    ]
