# Generated by Django 3.2.3 on 2021-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_alter_subject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='question_files/'),
        ),
    ]
