# Generated by Django 3.2.3 on 2021-05-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_alter_quiz_question_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='avg_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
